A Checkbox to switch which button confirms things.
puyonexus/puyovs pull request #19
Opened 2022-07-27 17:39 UTC by Xkower8181

A bit a small pet peeve of mine, which was a good thing to code in order to familiarize myself with the codebase more.
The only problem being is that the code (perhaps) is ugly. That's it.

2022-07-28 02:03 UTC, jchv requested changes
Mostly LGTM, but it looks like all of the code changes are using spaces instead of tabs. Up until very recently the code was inconsistent, but I've moved it to all use tabs. If possible, it would be most preferable to setup ClangFormat and run all files you're editing through it prior to merging. It will take care of this and other issues.

For Qt Creator, it needs to be enabled manually:

https://www.qt.io/blog/2019/04/17/clangformat-plugin-qt-creator-4-9

2022-07-28 02:03 UTC, jchv commented on Client/gamemanager.cpp
> +    gs->SwapABConfirm = settings.boolean("controlsp1", "swapabconfirm", true);
It looks like this is set to default to `true`. Presumably it should default to `false`.

2022-07-28 02:04 UTC, jchv commented
(It would be nicer if internally we swapped a designated 'confirm' button instead of having it handled at each place where a confirmation is made, but it's not trivial to do that right now, so that can wait until later.)

2022-07-31 17:55 UTC, Xkower8181 commented
I've done everything that you have mentioned plus an oversight that you missed in settingsdialog.ui where it automatically opened into the controls tab instead of general

2022-07-31 19:29 UTC, jchv approved these changes
OK, I ran the formatter because it was still weird, but otherwise everything is good to merge I think.

2022-07-31 19:30 UTC, merged